---
namespace: 'r_pufky'
name: 'lib'
version: '1.0.0'
readme: 'README.md'
authors:
  - 'Robert Pufky <rpufky@gmail.com> (https://github.com/r-pufky)'
description: |
  Provides common testing patterns and middleware for complex operations.
license_file: 'LICENSE'
tags:
  - 'ansible'
  - 'library'
  - 'utility'
  - 'tools'
dependencies:
  'community.general': '>=12.4.0,<13.0.0'

repository: 'https://github.com/r-pufky/ansible_collection_lib'
documentation: 'https://r-pufky.github.io/ansible_collection_docs'
homepage: 'https://github.com/r-pufky/ansible_collection_lib'
issues: 'https://github.com/r-pufky/ansible_collection_lib/issues'

# Do not include: testing, environments, caches, IDE settings, or staging
# messages in release tarball.
build_ignore:
  - '*.ansible'
  - '*.gitignore'
  - '*.gitmodules'
  - '*.git'
  - '*molecule'
  - '.envrc'
  - '.vscode'
  - 'ansible.env'
  - 'TODO.md'
  - 'COMMIT.md'
