---
namespace: 'r_pufky'
name: 'lib'
version: '13.0.8'
readme: 'README.md'
authors:
  - 'Robert Pufky <rpufky@gmail.com> (https://github.com/r-pufky)'
description: >
  Provides common testing patterns and middleware for complex operations.
license_file: 'LICENSE'
tags:
  - 'ansible'
  - 'library'
  - 'utility'
  - 'tools'
dependencies:
  'community.general': '=11.4.0'

repository: 'https://github.com/r-pufky/ansible_collection_lib'
documentation: 'https://r-pufky.github.io/ansible_collection_docs'
homepage: 'https://github.com/r-pufky/ansible_collection_lib'
issues: 'https://github.com/r-pufky/ansible_collection_lib/issues'

build_ignore:
  - '*molecule/*'  # Do not include molecule testing in release.
  - 'ansible.env'  # Development ansible environment.
  - '.ansible'  # Ansible collection cache for role testing.
  - '.vscode'  # VSCodium settings.
  - 'TODO.md'  # Development staging todo messages.
  - 'COMMIT.md'  # Development staging commit messages.
  - '*docs/*'  # Development docs are a separate repo and not end user.
